### ISSUE TITLE
Support for GFX100s

### ISSUE THREAD

**Issue by hardysgarage** [agriggio/make_arq#5]
Hi Albert, I don't believe this supports the GFX100s which should be very similar to the GFX100 files.  I tried to make it work by modifying the accepted camera models and it generated an ARQ output file which didn't seem to work.  Beyond my skill.  Hoping support for GFX100s could be added. :)

**Comment by agriggio** [comment]
Hi,
Can you provide sample files please? Just share via Dropbox or similar. Thanks!

**Comment by hardysgarage** [comment]
Here's a link with two sets of pixel shift images, 16 files in each folder.
https://ln5.sync.com/dl/1358efe90/hr4fjxgj-ru3mm5ys-iprr6k5m-t6pttf97
If any issues with them, please let me know.  Also, please let me know when you have downloaded the files and I'll delete the link again, about 3GB in total.  
Sorry the photo's aren't more interesting!

**Comment by agriggio** [comment]
got them, thanks!

**Comment by hardysgarage** [comment]
Thankyou!  Good luck!

**Comment by agriggio** [comment]
Hi, it should work now. Note you need the latest version of ART from the `master` branch to process the resulting `.arq` files though

**Comment by hardysgarage** [comment]
Fantastic!
