### ISSUE TITLE
Support for Sony Alpha 1

### ISSUE THREAD

**Issue by abrock** [agriggio/make_arq#6]
I tried to use this for images taken with a Sony Alpha 1 and it told me it can't do that. I took a couple of example pictures, both with full frame and with APSC-crop, both with 4x and with 16x (uploading should be done in an hour):

https://drive.google.com/drive/folders/1uLr24eDGNvRDVZznfHXzKRSsLgJayyI-?usp=share_link

The Alpha 7R V has the exact same sensor resolution as the 7R IV so that would probably work by just treating it the same, but I don't have examples.

**Comment by agriggio** [comment]
Hi, it should work now, at least for 4 frames (I do not have enough bandwidth at the moment to download the 16-frame samples :-)
Note though that you need the latest version of ART from the `master` branch to process the resulting `.arq` files.

**Comment by abrock** [comment]
It works, thank you very much. Could you point me to the relevant commits in ART which enable using the `.arq` files? I'd like to port them to RT if possible.

**Comment by agriggio** [comment]
Hi,
it's this:
https://bitbucket.org/agriggio/art/commits/fda5554d1146c2e3b1d804468fe0200d9398b775
