### ISSUE TITLE
recently only quater image for a7r4

### ISSUE THREAD

**Issue by bor-lin** [agriggio/make_arq#9]
I have tested three versions of make_arq:
1. installed on Nov 25 2020
2. installed on Feb 9 2023
3. installed on May 18 2023
on two (old and new) gentoo distributions.

old (2020):
python-3.7.8-r2
tifffile  2020.11.18
glibc-2.31-r6

new (2023):
python-3.9.16_p3 (can be switched to version python-3.10.11)
tifffile     2023.4.12
glibc-2.37-r2

<tifffile.TiffWriter 'out16-new-2.ARQ'> not writing extratag 258

Recent version of make_arq displays only quater image.
Only oldest make_arg on old gentoo displays full image.

https://drive.google.com/file/d/1iJwx1Mh-BLHi6RoFdn1Q7TyYzvOn1KgA/view?usp=sharing

**Comment by agriggio** [comment]
I tried and everything works fine here. What version of exiftool are you using? Also, this line looks suspicious:

> <tifffile.TiffWriter 'out16-new-2.ARQ'> not writing extratag 258

if you are getting that in the console, most likely you are not using the latest version of `make_arq.py`: are you sure you are up to date?

**Comment by bor-lin** [comment]
exiftool:
old gentoo (2020)  exiftool-12.01
new gentoo (February 2023) exiftool-12.61

" not writing extratag 258"
only on new gentoo only for version (2) of make_arq (this version which
displays in green: not
old version 2020 nor actual)

yes, up to date (I will now check again) - it is seen that version taken
about week ago displays "in green",
and version taken yesterday gives reasonably colours (but only "quarter")

**Comment by bor-lin** [comment]
checked, up to date version of make_arq

as seen old-Screenshot_20230520_085145.png
version (2) of make_arq (version taken about week ago, with green patterns
on
new gentoo) on old gentoo displays only quarter (but right colours due to
tifffile)

**Comment by bor-lin** [comment]
I have temporarily changed exiftool to the outdated version 12.50 -
still only quarter

**Comment by bor-lin** [comment]
I have put line print(offset) in function get_sony_frame_data.

def get_sony_frame_data(data, frame, idx, factor):
   filename, tags = frame
   width = tags['EXIF:ImageWidth']
   height = tags['EXIF:ImageHeight']
   offset = tags['EXIF:StripOffsets']
   print(offset)
   rowstart = 1 if (idx // 4) >= 2 else 0
   ........

Are offsets correct?

Reading frame: /mnt/part12/pshift2/DSC01004.ARW
724992
Reading frame: /mnt/part12/pshift2/DSC01003.ARW
729088
Reading frame: /mnt/part12/pshift2/DSC01006.ARW
729088
Reading frame: /mnt/part12/pshift2/DSC01005.ARW
729088
Reading frame: /mnt/part12/pshift2/DSC01000.ARW
724992
Reading frame: /mnt/part12/pshift2/DSC00999.ARW
733184
Reading frame: /mnt/part12/pshift2/DSC01002.ARW
729088
Reading frame: /mnt/part12/pshift2/DSC01001.ARW
729088
Reading frame: /mnt/part12/pshift2/DSC01012.ARW
724992
Reading frame: /mnt/part12/pshift2/DSC01011.ARW
720896
Reading frame: /mnt/part12/pshift2/DSC01014.ARW
729088
Reading frame: /mnt/part12/pshift2/DSC01013.ARW
729088
Reading frame: /mnt/part12/pshift2/DSC01008.ARW
729088
Reading frame: /mnt/part12/pshift2/DSC01007.ARW
729088
Reading frame: /mnt/part12/pshift2/DSC01010.ARW
724992
Reading frame: /mnt/part12/pshift2/DSC01009.ARW
729088

**Comment by bor-lin** [comment]
In this issue I have taken into account only
pure python make_arq.py (without python _makearq_setup.py build_ext
--inplace).
To see full image (not quarter) I had to apply
following patch:

diff make_arq-working.py make_arq.py
70a71
>
78c79
<                 if 0 <= rr < height * factor:
---
>                 if 0 <= rr < height:
82c83
<                         if 0 <= cc < width*factor:
---
>                         if 0 <= cc < width:

where make_arq.py is taken on May 20, 2023 from zip file.

I think that this issue has nothing in common with
exiftool (python, tifffile, etc) versions
and can be closed.
This program is really great.

**Comment by agriggio** [comment]
Hi,
thanks for your feedback, I did not test the pure python version indeed. I'll see if I can integrate your patch, thanks again!
